seed: 0
epsilon: 0.0
heuristic_type: Normal

terrain: null
spawn_mode: corner # corner, normal, uniform_hideout_dist  
random_cameras: False
# camera_file_path: simulator/camera_locations/70_per_cent_cameras_w_camera_net.txt
camera_file_path: simulator/camera_locations/original_no_camera_net.txt
mountain_locations:
  # - 400, 300
  - 1600, 1800
camera_range_factor: 0.5
observation_terrain_feature: False
random_hideout_locations: False
num_known_hideouts: 1
num_unknown_hideouts: 2 # 0, 2
spawn_range: 350
max_timesteps: 400 # in diffusion dataset: 250
helicopter_battery_life: 401 # 200
helicopter_recharge_time: 40
num_search_parties: 1
num_helicopters: 1
terrain_map: simulator/forest_coverage/map_set/2_darker.npy
step_reset: True
camera_net_bool: False
num_random_known_cameras: 30
num_random_unknown_cameras: 30
min_distance_from_hideout_to_start: null
min_distance_from_hideout_to_start: False
include_camera_at_start: True # False, True
include_start_location_blue_obs: False
store_last_k_fugitive_detections: True
gnn_agent_last_detect: "no"
search_party_speed: 20 # 20
helicopter_speed: 127 # 127
fugitive_speed: 15
detection_factor: 4.0 # 4.0
include_fugitive_location_in_blue_obs: False
comm_dim: 0
reward_setting: rl # rl, piece
known_hideout_locations:
  - 323, 1623
  - 1804, 737
  - 317, 2028
  - 819, 1615
  - 1145, 182
  - 1304, 624
  - 234, 171
  - 2398, 434
  - 633, 2136
  - 1590, 2

unknown_hideout_locations:
  - 376, 1190
  - 909, 510
  - 397, 798
  - 2059, 541
  - 2011, 103
  - 901, 883
  - 1077, 1445
  - 602, 372
  - 80, 2274
  - 279, 477